// <auto-generated />
using System;
using GrowingPlants.DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GrowingPlants.DataAccess.Migrations
{
    [DbContext(typeof(GrowingPlantsContext))]
    [Migration("20200930063121_AddMoreTreeData")]
    partial class AddMoreTreeData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Country");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.FavoriteTree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<int?>("TreeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TreeId");

                    b.HasIndex("UserId");

                    b.ToTable("FavoriteTree");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.Gallery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlantingProcessId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlantingProcessId")
                        .IsUnique()
                        .HasFilter("[PlantingProcessId] IS NOT NULL");

                    b.ToTable("Gallery");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.Humidity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromUnit")
                        .HasColumnType("int");

                    b.Property<int?>("MeasurementUnitId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToUnit")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementUnitId");

                    b.ToTable("Humidity");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.Light", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromUnit")
                        .HasColumnType("int");

                    b.Property<int?>("MeasurementUnitId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToUnit")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementUnitId");

                    b.ToTable("Light");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.MeasurementUnit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MeasurementUnit");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Notification");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.Picture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("GalleryId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Source")
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GalleryId");

                    b.ToTable("Picture");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.PlantType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("PlantType");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.PlantingAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("ActionTime")
                        .HasColumnType("datetime2");

                    b.Property<double>("Amount")
                        .HasColumnType("float");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MeasurementUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProcessStepId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProcessStepId");

                    b.ToTable("PlantingAction");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.PlantingEnvironment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnvironmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExposureTime")
                        .HasColumnType("int");

                    b.Property<string>("Humidity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Length")
                        .HasColumnType("int");

                    b.Property<string>("Light")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Temperature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("Width")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("UserId");

                    b.ToTable("PlantingEnvironment");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.PlantingProcess", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FloweringDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("GerminationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HarvestDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PlantingSpotId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TreeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("VegetativeDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlantingSpotId");

                    b.HasIndex("TreeId");

                    b.HasIndex("UserId");

                    b.ToTable("PlantingProcess");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.PlantingSpot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("PlantingEnvironmentId")
                        .HasColumnType("int");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<int?>("TreeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlantingEnvironmentId");

                    b.HasIndex("TreeId");

                    b.ToTable("PlantingSpot");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.ProcessStep", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlantingProcessId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PlantingProcessId");

                    b.ToTable("ProcessStep");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.Recurrence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Days")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProcessStepId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProcessStepId");

                    b.ToTable("Recurrence");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.Temperature", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FromDegree")
                        .HasColumnType("int");

                    b.Property<int?>("MeasurementUnitId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ToDegree")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MeasurementUnitId");

                    b.ToTable("Temperature");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.Tree", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ComparisonAgainst")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ComparisonWith")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnvironmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ExposureTime")
                        .HasColumnType("int");

                    b.Property<int>("FloweringTime")
                        .HasColumnType("int");

                    b.Property<int>("GerminationTime")
                        .HasColumnType("int");

                    b.Property<int>("HarvestTime")
                        .HasColumnType("int");

                    b.Property<string>("Humidity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Light")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PictureId")
                        .HasColumnType("int");

                    b.Property<string>("PlantType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlantingGuide")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Temperature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("VegetativeTime")
                        .HasColumnType("int");

                    b.Property<int>("WaterLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PictureId");

                    b.ToTable("Tree");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ComparisonAgainst = "Unknown",
                            ComparisonWith = "Unknown",
                            CreatedAt = new DateTime(2020, 8, 30, 9, 49, 0, 0, DateTimeKind.Unspecified),
                            Description = "Chamaecyparis lawsoniana, known as Port Orford cedar or Lawson cypress, is a species of conifer in the genus Chamaecyparis, family Cupressaceae. It is native to Oregon and northwestern California, and grows from sea level up to 1,500 m (4,900 ft) in the valleys of the Klamath Mountains, often along streams",
                            EnvironmentType = "Outdoor",
                            ExposureTime = 5,
                            FloweringTime = 12,
                            GerminationTime = 24,
                            HarvestTime = 30,
                            Humidity = "47",
                            Light = "88",
                            Name = "Chamaecyparis lawsoniana",
                            PlantType = "Tree",
                            PlantingGuide = "Just water it",
                            Temperature = "36 Degree",
                            VegetativeTime = 7,
                            WaterLevel = 8
                        },
                        new
                        {
                            Id = 2,
                            ComparisonAgainst = "Unknown",
                            ComparisonWith = "Unknown",
                            CreatedAt = new DateTime(2020, 8, 30, 9, 49, 0, 0, DateTimeKind.Unspecified),
                            Description = "The blackberry is an edible fruit made by any of several species in the Rubus genus of the Rosaceae family. The blackberry shrub is called 'bramble' in Britain, but in the western U.S. 'caneberry' is the term is used for both blackberries and raspberries",
                            EnvironmentType = "Indoor",
                            ExposureTime = 15,
                            FloweringTime = 32,
                            GerminationTime = 45,
                            HarvestTime = 23,
                            Humidity = "49",
                            Light = "48",
                            Name = "Blackberry",
                            PlantType = "Fruit",
                            PlantingGuide = "Just water it",
                            Temperature = "16 Degree",
                            VegetativeTime = 4,
                            WaterLevel = 14
                        },
                        new
                        {
                            Id = 3,
                            ComparisonAgainst = "Unknown",
                            ComparisonWith = "Unknown",
                            CreatedAt = new DateTime(2020, 8, 30, 9, 49, 0, 0, DateTimeKind.Unspecified),
                            Description = "The apple tree (Malus domestica) is a tree that grows fruit (such as apples) in the rose family best known for its juicy, tasty fruit. It is grown worldwide as a fruit tree. It is considered to be a low-cost fruit harvestable all over the world.",
                            EnvironmentType = "Indoor",
                            ExposureTime = 65,
                            FloweringTime = 12,
                            GerminationTime = 65,
                            HarvestTime = 10,
                            Humidity = "19",
                            Light = "49",
                            Name = "Apple",
                            PlantType = "Fruit",
                            PlantingGuide = "Just water it",
                            Temperature = "16 Degree",
                            VegetativeTime = 36,
                            WaterLevel = 24
                        },
                        new
                        {
                            Id = 4,
                            ComparisonAgainst = "Unknown",
                            ComparisonWith = "Unknown",
                            CreatedAt = new DateTime(2020, 8, 30, 9, 49, 0, 0, DateTimeKind.Unspecified),
                            Description = "The pineapple is a fruit. It is native to South America, Central America and the Caribbean. The word 'pineapple' came from European explorers, who thought the fruit looked similar to a pine cone.",
                            EnvironmentType = "Indoor",
                            ExposureTime = 11,
                            FloweringTime = 34,
                            GerminationTime = 32,
                            HarvestTime = 15,
                            Humidity = "15",
                            Light = "2",
                            Name = "Pineapple",
                            PlantType = "Fruit",
                            PlantingGuide = "Just water it",
                            Temperature = "16 Degree",
                            VegetativeTime = 31,
                            WaterLevel = 22
                        },
                        new
                        {
                            Id = 5,
                            ComparisonAgainst = "Unknown",
                            ComparisonWith = "Unknown",
                            CreatedAt = new DateTime(2020, 8, 30, 9, 49, 0, 0, DateTimeKind.Unspecified),
                            Description = "A banana is the common name for a type of fruit and also the name for the herbaceous plants that grow it. These plants belong to the genus Musa. They are native to the tropical region of southeast Asia.",
                            EnvironmentType = "Outdoor",
                            ExposureTime = 12,
                            FloweringTime = 12,
                            GerminationTime = 12,
                            HarvestTime = 15,
                            Humidity = "55",
                            Light = "10",
                            Name = "Banana",
                            PlantType = "Fruit",
                            PlantingGuide = "Just water it",
                            Temperature = "50 Degree",
                            VegetativeTime = 32,
                            WaterLevel = 4
                        },
                        new
                        {
                            Id = 6,
                            ComparisonAgainst = "Unknown",
                            ComparisonWith = "Unknown",
                            CreatedAt = new DateTime(2020, 8, 30, 9, 49, 0, 0, DateTimeKind.Unspecified),
                            Description = "Umbellularia californica is a large hardwood tree native to coastal forests and the Sierra foothills of California, as well as to coastal forests extending into Oregon. It is endemic to the California Floristic Province. It is the sole species in the genus Umbellularia.",
                            EnvironmentType = "Outdoor",
                            ExposureTime = 5,
                            FloweringTime = 12,
                            GerminationTime = 24,
                            HarvestTime = 30,
                            Humidity = "47",
                            Light = "88",
                            Name = "Umbellularia",
                            PlantType = "Herb",
                            PlantingGuide = "Just water it",
                            Temperature = "36 Degree",
                            VegetativeTime = 7,
                            WaterLevel = 8
                        },
                        new
                        {
                            Id = 7,
                            ComparisonAgainst = "Unknown",
                            ComparisonWith = "Unknown",
                            CreatedAt = new DateTime(2020, 8, 30, 9, 49, 0, 0, DateTimeKind.Unspecified),
                            Description = "Myrrhis odorata, with common names cicely (/ˈsɪsəli/), sweet cicely, myrrh, garden myrrh, and sweet chervil, is a herbaceous perennial plant belonging to the celery family Apiaceae. It is one of two accepted species in the genus Myrrhis.",
                            EnvironmentType = "Indoor",
                            ExposureTime = 15,
                            FloweringTime = 32,
                            GerminationTime = 45,
                            HarvestTime = 23,
                            Humidity = "49",
                            Light = "48",
                            Name = "Cicely",
                            PlantType = "Herb",
                            PlantingGuide = "Just water it",
                            Temperature = "16 Degree",
                            VegetativeTime = 4,
                            WaterLevel = 14
                        },
                        new
                        {
                            Id = 8,
                            ComparisonAgainst = "Unknown",
                            ComparisonWith = "Unknown",
                            CreatedAt = new DateTime(2020, 8, 30, 9, 49, 0, 0, DateTimeKind.Unspecified),
                            Description = "Thai basil (Thai: โหระพา, RTGS: horapha, ISO: h̄oraphā, pronounced [hǒː.rá(ʔ).pʰāː]; Vietnamese: húng quế; in Taiwan: 九層塔) is a type of basil native to Southeast Asia that has been cultivated to provide distinctive traits. Widely used throughout Southeast Asia, its flavor, described as anise- and licorice-like and slightly spicy, is more stable under high or extended cooking temperatures than that of sweet basil. Thai basil has small, narrow leaves, purple stems, and pink-purple flowers.",
                            EnvironmentType = "Outdoor",
                            ExposureTime = 65,
                            FloweringTime = 12,
                            GerminationTime = 65,
                            HarvestTime = 10,
                            Humidity = "19",
                            Light = "49",
                            Name = "Thai basil",
                            PlantType = "Herb",
                            PlantingGuide = "Just water it",
                            Temperature = "16 Degree",
                            VegetativeTime = 36,
                            WaterLevel = 24
                        },
                        new
                        {
                            Id = 9,
                            ComparisonAgainst = "Unknown",
                            ComparisonWith = "Unknown",
                            CreatedAt = new DateTime(2020, 8, 30, 9, 49, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ajwain, ajowan[3] (/ˈædʒəwɒn/), or Trachyspermum ammi—also known as ajowan caraway, bishop's weed,[4] or carom—is an annual herb in the family Apiaceae (or Umbelliferae). Both the leaves and the seed‑like fruit (often mistakenly called seeds) of the plant are consumed by humans. The name \"bishop's weed\" also is a common name for other plants. The \"seed\" (i.e., the fruit) is often confused with lovage \"seed\"",
                            EnvironmentType = "Indoor",
                            ExposureTime = 11,
                            FloweringTime = 34,
                            GerminationTime = 32,
                            HarvestTime = 15,
                            Humidity = "15",
                            Light = "2",
                            Name = "Ajwain",
                            PlantType = "Herb",
                            PlantingGuide = "Just water it",
                            Temperature = "16 Degree",
                            VegetativeTime = 31,
                            WaterLevel = 22
                        },
                        new
                        {
                            Id = 10,
                            ComparisonAgainst = "Unknown",
                            ComparisonWith = "Unknown",
                            CreatedAt = new DateTime(2020, 8, 30, 9, 49, 0, 0, DateTimeKind.Unspecified),
                            Description = "Hornbeams are hardwood trees in the flowering plant genus Carpinus in the birch family Betulaceae. The 30–40 species occur across much of the temperate regions of the Northern Hemisphere.",
                            EnvironmentType = "Outdoor",
                            ExposureTime = 12,
                            FloweringTime = 12,
                            GerminationTime = 12,
                            HarvestTime = 15,
                            Humidity = "55",
                            Light = "10",
                            Name = "Hornbeam",
                            PlantType = "Tree",
                            PlantingGuide = "Just water it",
                            Temperature = "50 Degree",
                            VegetativeTime = 32,
                            WaterLevel = 4
                        },
                        new
                        {
                            Id = 11,
                            ComparisonAgainst = "Unknown",
                            ComparisonWith = "Unknown",
                            CreatedAt = new DateTime(2020, 8, 30, 9, 49, 0, 0, DateTimeKind.Unspecified),
                            Description = "A mango is a type of fruit. The mango tree is native to South Asia, from where it has been taken to become one of the most widely cultivated fruits in the tropics.It is harvested in the month of march (summer season) till the end of May.",
                            EnvironmentType = "Outdoor",
                            ExposureTime = 5,
                            FloweringTime = 12,
                            GerminationTime = 24,
                            HarvestTime = 30,
                            Humidity = "47",
                            Light = "88",
                            Name = "Mango",
                            PlantType = "Fruit",
                            PlantingGuide = "Just water it",
                            Temperature = "36 Degree",
                            VegetativeTime = 7,
                            WaterLevel = 8
                        },
                        new
                        {
                            Id = 12,
                            ComparisonAgainst = "Unknown",
                            ComparisonWith = "Unknown",
                            CreatedAt = new DateTime(2020, 8, 30, 9, 49, 0, 0, DateTimeKind.Unspecified),
                            Description = "The lemon is a small tree (Citrus limon) that is green even in the winter. It came from Asia, and is also the name of the tree's oval-shaped yellow fruit.",
                            EnvironmentType = "Indoor",
                            ExposureTime = 15,
                            FloweringTime = 32,
                            GerminationTime = 45,
                            HarvestTime = 23,
                            Humidity = "49",
                            Light = "48",
                            Name = "Lemon",
                            PlantType = "Fruit",
                            PlantingGuide = "Just water it",
                            Temperature = "16 Degree",
                            VegetativeTime = 4,
                            WaterLevel = 14
                        },
                        new
                        {
                            Id = 13,
                            ComparisonAgainst = "Unknown",
                            ComparisonWith = "Unknown",
                            CreatedAt = new DateTime(2020, 8, 30, 9, 49, 0, 0, DateTimeKind.Unspecified),
                            Description = "The peach is a species of the Prunus persica, and is a fruit tree of the rose family Rosaceae. They grow in the warm regions of both the northern and southern hemispheres.",
                            EnvironmentType = "Indoor",
                            ExposureTime = 65,
                            FloweringTime = 12,
                            GerminationTime = 65,
                            HarvestTime = 10,
                            Humidity = "19",
                            Light = "49",
                            Name = "Peach",
                            PlantType = "Fruit",
                            PlantingGuide = "Just water it",
                            Temperature = "16 Degree",
                            VegetativeTime = 36,
                            WaterLevel = 24
                        },
                        new
                        {
                            Id = 14,
                            ComparisonAgainst = "Unknown",
                            ComparisonWith = "Unknown",
                            CreatedAt = new DateTime(2020, 8, 30, 9, 49, 0, 0, DateTimeKind.Unspecified),
                            Description = "Papaya is a tall herbaceous plant in the genus Carica; its edible fruit is also called papaya. It is native to the tropical region of America, mainly from southern Mexico to Central America. Now these plants are grown in all tropical regions of the world",
                            EnvironmentType = "Indoor",
                            ExposureTime = 11,
                            FloweringTime = 34,
                            GerminationTime = 32,
                            HarvestTime = 15,
                            Humidity = "15",
                            Light = "2",
                            Name = "Papaya",
                            PlantType = "Fruit",
                            PlantingGuide = "Just water it",
                            Temperature = "16 Degree",
                            VegetativeTime = 31,
                            WaterLevel = 22
                        },
                        new
                        {
                            Id = 15,
                            ComparisonAgainst = "Unknown",
                            ComparisonWith = "Unknown",
                            CreatedAt = new DateTime(2020, 8, 30, 9, 49, 0, 0, DateTimeKind.Unspecified),
                            Description = "Jackfruit (also called \"Jakfruit\") is a type of fruit from India, Bangladesh (National fruit)[source?] and Sri Lanka.[1] When a Jackfruit ripens, it changes from green to slightly yellow.",
                            EnvironmentType = "Outdoor",
                            ExposureTime = 12,
                            FloweringTime = 12,
                            GerminationTime = 12,
                            HarvestTime = 15,
                            Humidity = "55",
                            Light = "10",
                            Name = "Jackfruit",
                            PlantType = "Fruit",
                            PlantingGuide = "Just water it",
                            Temperature = "50 Degree",
                            VegetativeTime = 32,
                            WaterLevel = 4
                        },
                        new
                        {
                            Id = 16,
                            ComparisonAgainst = "Unknown",
                            ComparisonWith = "Unknown",
                            CreatedAt = new DateTime(2020, 8, 30, 9, 49, 0, 0, DateTimeKind.Unspecified),
                            Description = "A melon is any kind of edible, fleshy fruit in the Cucurbitaceae family. Many different cultivars have been produced, especially of muskmelons. Botanically speaking, the melon is a fruit, but some kinds are often considered vegetables. Most melons belong to the genus Cucumis, but there are also some that belong to Benincasa, Citrullus and Momordica. The muskmelon belongs to Cucumis, while the watermelon belongs to Citrullus",
                            EnvironmentType = "Outdoor",
                            ExposureTime = 5,
                            FloweringTime = 12,
                            GerminationTime = 24,
                            HarvestTime = 30,
                            Humidity = "47",
                            Light = "88",
                            Name = "Melon",
                            PlantType = "Fruit",
                            PlantingGuide = "Just water it",
                            Temperature = "36 Degree",
                            VegetativeTime = 7,
                            WaterLevel = 8
                        },
                        new
                        {
                            Id = 17,
                            ComparisonAgainst = "Unknown",
                            ComparisonWith = "Unknown",
                            CreatedAt = new DateTime(2020, 8, 30, 9, 49, 0, 0, DateTimeKind.Unspecified),
                            Description = "The tomato (Solanum lycopersicum) is a botanical fruit (but not a fruit as ordinary people use the word).",
                            EnvironmentType = "Indoor",
                            ExposureTime = 15,
                            FloweringTime = 32,
                            GerminationTime = 45,
                            HarvestTime = 23,
                            Humidity = "49",
                            Light = "48",
                            Name = "Tomato",
                            PlantType = "Fruit",
                            PlantingGuide = "Just water it",
                            Temperature = "16 Degree",
                            VegetativeTime = 4,
                            WaterLevel = 14
                        },
                        new
                        {
                            Id = 18,
                            ComparisonAgainst = "Unknown",
                            ComparisonWith = "Unknown",
                            CreatedAt = new DateTime(2020, 8, 30, 9, 49, 0, 0, DateTimeKind.Unspecified),
                            Description = "Longan (scientific name: Dimocarpus longan) is the name for a tree in the Sapindaceae (soapberry) family. It comes from the southern part of Asia and is related to the lychee.",
                            EnvironmentType = "Outdoor",
                            ExposureTime = 65,
                            FloweringTime = 12,
                            GerminationTime = 65,
                            HarvestTime = 10,
                            Humidity = "19",
                            Light = "49",
                            Name = "Longan",
                            PlantType = "Herb",
                            PlantingGuide = "Just water it",
                            Temperature = "16 Degree",
                            VegetativeTime = 36,
                            WaterLevel = 24
                        },
                        new
                        {
                            Id = 19,
                            ComparisonAgainst = "Unknown",
                            ComparisonWith = "Unknown",
                            CreatedAt = new DateTime(2020, 8, 30, 9, 49, 0, 0, DateTimeKind.Unspecified),
                            Description = "Apricot is a drupe fruit. It is closely related to the plum.",
                            EnvironmentType = "Indoor",
                            ExposureTime = 11,
                            FloweringTime = 34,
                            GerminationTime = 32,
                            HarvestTime = 15,
                            Humidity = "15",
                            Light = "2",
                            Name = "Apricot",
                            PlantType = "Fruit",
                            PlantingGuide = "Just water it",
                            Temperature = "16 Degree",
                            VegetativeTime = 31,
                            WaterLevel = 22
                        },
                        new
                        {
                            Id = 20,
                            ComparisonAgainst = "Unknown",
                            ComparisonWith = "Unknown",
                            CreatedAt = new DateTime(2020, 8, 30, 9, 49, 0, 0, DateTimeKind.Unspecified),
                            Description = "The coconut palm is a palm tree in the family Arecaceae (palm family). It is a large palm, growing to 30 m tall. It has leaves that are 4–6 m long. The term coconut refers to the fruit of the coconut palm. The coconut tree is a monocot.",
                            EnvironmentType = "Outdoor",
                            ExposureTime = 12,
                            FloweringTime = 12,
                            GerminationTime = 12,
                            HarvestTime = 15,
                            Humidity = "55",
                            Light = "10",
                            Name = "Coconut",
                            PlantType = "Tree",
                            PlantingGuide = "Just water it",
                            Temperature = "50 Degree",
                            VegetativeTime = 32,
                            WaterLevel = 4
                        });
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.FavoriteTree", b =>
                {
                    b.HasOne("GrowingPlants.Infrastructure.Models.Tree", "Tree")
                        .WithMany("FavoriteTrees")
                        .HasForeignKey("TreeId");

                    b.HasOne("GrowingPlants.Infrastructure.Models.User", "User")
                        .WithMany("FavoriteTrees")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.Gallery", b =>
                {
                    b.HasOne("GrowingPlants.Infrastructure.Models.PlantingProcess", "PlantingProcess")
                        .WithOne("Gallery")
                        .HasForeignKey("GrowingPlants.Infrastructure.Models.Gallery", "PlantingProcessId");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.Humidity", b =>
                {
                    b.HasOne("GrowingPlants.Infrastructure.Models.MeasurementUnit", "MeasurementUnit")
                        .WithMany()
                        .HasForeignKey("MeasurementUnitId");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.Light", b =>
                {
                    b.HasOne("GrowingPlants.Infrastructure.Models.MeasurementUnit", "MeasurementUnit")
                        .WithMany()
                        .HasForeignKey("MeasurementUnitId");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.Picture", b =>
                {
                    b.HasOne("GrowingPlants.Infrastructure.Models.Gallery", "Gallery")
                        .WithMany("Pictures")
                        .HasForeignKey("GalleryId");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.PlantingAction", b =>
                {
                    b.HasOne("GrowingPlants.Infrastructure.Models.ProcessStep", "ProcessStep")
                        .WithMany("PlantingActions")
                        .HasForeignKey("ProcessStepId");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.PlantingEnvironment", b =>
                {
                    b.HasOne("GrowingPlants.Infrastructure.Models.Country", null)
                        .WithMany("PlantingEnvironments")
                        .HasForeignKey("CountryId");

                    b.HasOne("GrowingPlants.Infrastructure.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.PlantingProcess", b =>
                {
                    b.HasOne("GrowingPlants.Infrastructure.Models.PlantingSpot", "PlantingSpot")
                        .WithMany()
                        .HasForeignKey("PlantingSpotId");

                    b.HasOne("GrowingPlants.Infrastructure.Models.Tree", "Tree")
                        .WithMany("PlantingProcesses")
                        .HasForeignKey("TreeId");

                    b.HasOne("GrowingPlants.Infrastructure.Models.User", "User")
                        .WithMany("PlantingProcesses")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.PlantingSpot", b =>
                {
                    b.HasOne("GrowingPlants.Infrastructure.Models.PlantingEnvironment", "PlantingEnvironment")
                        .WithMany("PlantingSpots")
                        .HasForeignKey("PlantingEnvironmentId");

                    b.HasOne("GrowingPlants.Infrastructure.Models.Tree", "Tree")
                        .WithMany()
                        .HasForeignKey("TreeId");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.ProcessStep", b =>
                {
                    b.HasOne("GrowingPlants.Infrastructure.Models.PlantingProcess", "PlantingProcess")
                        .WithMany("ProcessSteps")
                        .HasForeignKey("PlantingProcessId");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.Recurrence", b =>
                {
                    b.HasOne("GrowingPlants.Infrastructure.Models.ProcessStep", "ProcessStep")
                        .WithMany()
                        .HasForeignKey("ProcessStepId");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.Temperature", b =>
                {
                    b.HasOne("GrowingPlants.Infrastructure.Models.MeasurementUnit", "MeasurementUnit")
                        .WithMany()
                        .HasForeignKey("MeasurementUnitId");
                });

            modelBuilder.Entity("GrowingPlants.Infrastructure.Models.Tree", b =>
                {
                    b.HasOne("GrowingPlants.Infrastructure.Models.Picture", "Picture")
                        .WithMany()
                        .HasForeignKey("PictureId");
                });
#pragma warning restore 612, 618
        }
    }
}
